### PR TITLE
Add Scheduling & Handle Holiday Punch Card URL Return

### PR DESCRIPTION
**Pull request by njhughesSAS**
This will add scheduling for a random hour between 7-10 at a random min for the next day.

This will also handle the current holiday punch card random return URL happening from Microsoft.

### CODE REVIEW

**Review by njhughesSAS — COMMENTED** [review]
Fixed indention in run for multiple accounts

**Comment by charlesbel** [comment]
The scheduling is not so usefull, it is not the goal of the script to shedule himself. The scheduling should be maked by other softs or system configuration. But thanks for the suggestion

**Comment by njhughesSAS** [comment]
Just curious why opt for software based scheduling?

**Comment by charlesbel** [comment]
> Just curious why opt for software based scheduling?

A system task or a soft sheduling would be a better idea because it avoid overloading the RAM of the computer and avoid crashing on long time powered on

**Comment by njhughesSAS** [comment]
Totally makes sense I'll look into adding jitter to a Windows task and can add instructions to readme

**Pull request closed without merging**
