### PR TITLE
Add Shopping Game

### LINKED ISSUE #305: Bing Shopping
Bing shopping has a game where you pick what you think costs the least, this game can be visited at https://www.bing.com/shop however a more minimal version of it can be accessed at https://www.msn.com/en-us/shopping?isembedded=1&disableheader=1

This game only gives you points when you get it correct, which for a human is very easy as you can simply click on see more to open the price in a new page. However we don't want to have to do that in the bot.

One method I attempted was to navigate the dom to get to the `msn-shopping-game-pane` and then searching the `displayedShoppingEntities` field.
```js
let gamePane = document.querySelector('shopping-page-base').shadowRoot.querySelector('shopping-homepage').shadowRoot.querySelector('msft-feed-layout').shadowRoot.querySelector('msn-shopping-game-pane');
let cheapest = gamePane.displayedShoppingEntities.sort((a, b) => parseFloat(a.priceInfo.price) < parseFloat(b.priceInfo.price))[0];
```

However, if you attempt to use that yourself. It does not show the cheapest item. If we look into this we notice that the price field is an empty string. ~~It seems that Microsoft has an "anti-cheat" of sort that they have added.~~ (I thought I had found a function but it actually doesn't seem to be called...

Either way, the price is an empty string; So that won't work. However I did notice we have a couple things stating the discount percentage... Now this is nowhere near perfect. But I think it'll do for now (I went through my 10 per day so I can't keep testing)
```js
let gamePane = document.querySelector('shopping-page-base').shadowRoot.querySelector('shopping-homepage').shadowRoot.querySelector('msft-feed-layout').shadowRoot.querySelector('msn-shopping-game-pane');
/*
// You can do this for faster ending games, however we won't use this in production
gamePane.gameSettings = { "newGameCountdown": 0 }
*/
for (const ent of gamePane.displayedShoppingEntities) {
    let originalPrice = parseFloat(ent.priceInfo.originalPrice.slice(ent.priceInfo.priceCurrencySymbol.length))
    let discountedPrice = originalPrice * (1 - parseFloat(ent.dealPercentage) / 100)
    console.log(discountedPrice)
}
```

So one thing I also noticed, the game must still be storing the original prices somewhere as it shows you them at the end of the game. That should be looked into to see how it's being done.

### PR DESCRIPTION
**Pull request by EastArctica**
Hi! This is my work in progress shopping game automation. It's a little bit iffy about it working. Hence the work in progress. If anyone has any questions please feel free to ask.

Fixes #305

### CODE REVIEW

**Comment by klept0** [comment]
[INFO] [SHOPPING GAME] Trying to complete the Shopping Game...←[0m
[ERROR] JavascriptException: Message: javascript error: Cannot read properties of null (reading 'querySelector')
JavaScript stack:
TypeError: Cannot read properties of null (reading 'querySelector')
    at eval (eval at executeAsyncScript (:443:26), <anonymous>:55:38)
  (Session info: chrome=116.0.5845.112)
Stacktrace:
        GetHandleVerifier [0x011A37C3+48947]
        (No symbol) [0x01138551]
        (No symbol) [0x0103C92D]
        (No symbol) [0x0104170B]
        (No symbol) [0x010412D2]
        (No symbol) [0x010981A0]
        (No symbol) [0x0108508C]
        (No symbol) [0x010975DA]
        (No symbol) [0x01084E86]
        (No symbol) [0x010616C7]
        (No symbol) [0x0106284D]
        GetHandleVerifier [0x013EFDF9+2458985]
        GetHandleVerifier [0x0143744F+2751423]
        GetHandleVerifier [0x01431361+2726609]
        GetHandleVerifier [0x01220680+560624]
        (No symbol) [0x0114238C]
        (No symbol) [0x0113E268]
        (No symbol) [0x0113E392]
        (No symbol) [0x011310B7]
        BaseThreadInitThunk [0x76226BA9+25]
        RtlGetFullPathName_UEx [0x76F78F9F+1215]
        RtlGetFullPathName_UEx [0x76F78F6D+1165]
        
        Traceback (most recent call last):
  File "C:\Microsoft-Rewards-Farmer-master\main.py", line 32, in main executeBot(currentAccount, notifier, args)
  File "C:\Microsoft-Rewards-Farmer-master\main.py", line 141, in executeBot
    ShoppingGame(desktopBrowser).completeShoppingGame()
  File "C:\Microsoft-Rewards-Farmer-master\src\shoppingGame.py", line 23, in completeShoppingGame
    res = self.webdriver.execute_async_script(
  File "C:\Users\AAA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute_async_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "C:\Users\AAA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\AAA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'querySelector')
JavaScript stack:
TypeError: Cannot read properties of null (reading 'querySelector')
    at eval (eval at executeAsyncScript (:443:26), <anonymous>:55:38)
  (Session info: chrome=116.0.5845.112)
Stacktrace:
        GetHandleVerifier [0x011A37C3+48947]
        (No symbol) [0x01138551]
        (No symbol) [0x0103C92D]
        (No symbol) [0x0104170B]
        (No symbol) [0x010412D2]
        (No symbol) [0x010981A0]
        (No symbol) [0x0108508C]
        (No symbol) [0x010975DA]
        (No symbol) [0x01084E86]
        (No symbol) [0x010616C7]
        (No symbol) [0x0106284D]
        GetHandleVerifier [0x013EFDF9+2458985]
        GetHandleVerifier [0x0143744F+2751423]
        GetHandleVerifier [0x01431361+2726609]
        GetHandleVerifier [0x01220680+560624]
        (No symbol) [0x0114238C]
        (No symbol) [0x0113E268]
        (No symbol) [0x0113E392]
        (No symbol) [0x011310B7]
        BaseThreadInitThunk [0x76226BA9+25]
        RtlGetFullPathName_UEx [0x76F78F9F+1215]
        RtlGetFullPathName_UEx [0x76F78F6D+1165]

**Comment by Chappie18** [comment]
displaying an error like this



image

**Comment by klept0** [comment]
Looks like the code changed a bit or it's obfuscated because it gets stuck with this method and the manual method I used before

**Comment by EastArctica** [comment]
> Looks like the code changed a bit or it's obfuscated because it gets stuck with this method and the manual method I used before

Nah, no obfuscation or issues on my end. 

> displaying an error like this
> 
> image

My bad, that error was supposed to be `[SHOPPING GAME] Failed to select cheapest item.` which happens when it fails to find the button you'd usually click to select your answer.


> [INFO] [SHOPPING GAME] Trying to complete the Shopping Game...←[0m [ERROR] JavascriptException: Message: javascript error: Cannot read properties of null (reading 'querySelector') JavaScript stack: TypeError: Cannot read properties of null (reading 'querySelector') at eval (eval at executeAsyncScript (:443:26), :55:38) (Session info: chrome=116.0.5845.112) Stacktrace: GetHandleVerifier [0x011A37C3+48947] (No symbol) [0x01138551] (No symbol) [0x0103C92D] (No symbol) [0x0104170B] (No symbol) [0x010412D2] (No symbol) [0x010981A0] (No symbol) [0x0108508C] (No symbol) [0x010975DA] (No symbol) [0x01084E86] (No symbol) [0x010616C7] (No symbol) [0x0106284D] GetHandleVerifier [0x013EFDF9+2458985] GetHandleVerifier [0x0143744F+2751423] GetHandleVerifier [0x01431361+2726609] GetHandleVerifier [0x01220680+560624] (No symbol) [0x0114238C] (No symbol) [0x0113E268] (No symbol) [0x0113E392] (No symbol) [0x011310B7] BaseThreadInitThunk [0x76226BA9+25] RtlGetFullPathName_UEx [0x76F78F9F+1215] RtlGetFullPathName_UEx [0x76F78F6D+1165]
> 
> Traceback (most recent call last): File "C:\Microsoft-Rewards-Farmer-master\main.py", line 32, in main executeBot(currentAccount, notifier, args) File "C:\Microsoft-Rewards-Farmer-master\main.py", line 141, in executeBot ShoppingGame(desktopBrowser).completeShoppingGame() File "C:\Microsoft-Rewards-Farmer-master\src\shoppingGame.py", line 23, in completeShoppingGame res = self.webdriver.execute_async_script( File "C:\Users\AAA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 424, in execute_async_script return self.execute(command, {"script": script, "args": converted_args})["value"] File "C:\Users\AAA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute self.error_handler.check_response(response) File "C:\Users\AAA\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'querySelector') JavaScript stack: TypeError: Cannot read properties of null (reading 'querySelector') at eval (eval at executeAsyncScript (:443:26), :55:38) (Session info: chrome=116.0.5845.112) Stacktrace: GetHandleVerifier [0x011A37C3+48947] (No symbol) [0x01138551] (No symbol) [0x0103C92D] (No symbol) [0x0104170B] (No symbol) [0x010412D2] (No symbol) [0x010981A0] (No symbol) [0x0108508C] (No symbol) [0x010975DA] (No symbol) [0x01084E86] (No symbol) [0x010616C7] (No symbol) [0x0106284D] GetHandleVerifier [0x013EFDF9+2458985] GetHandleVerifier [0x0143744F+2751423] GetHandleVerifier [0x01431361+2726609] GetHandleVerifier [0x01220680+560624] (No symbol) [0x0114238C] (No symbol) [0x0113E268] (No symbol) [0x0113E392] (No symbol) [0x011310B7] BaseThreadInitThunk [0x76226BA9+25] RtlGetFullPathName_UEx [0x76F78F9F+1215] RtlGetFullPathName_UEx [0x76F78F6D+1165]

Odd one, unsure what's wrong here... That's not even a line that calls `querySelector` in the latest code.

**Comment by Chappie18** [comment]
You can examine this script to determine what is lacking.
https://www.reddit.com/user/RohanPhuyal/comments/164pol8/msn_shopping_game_script_new/

**Comment by theskid31** [comment]
> @theskid31, Can you try the latest commit?

hi ,tried it seems to get stuck after loading page then skips onto next step Daily set
the first commit i got a message :[SHOPPING GAME] Failed to get game element.
but nothing on that run just skipped to the daily set

> ←[38;5;39m2023-08-31 15:31:22,261 [INFO] Using default request storage←[0m
←[38;5;39m2023-08-31 15:31:22,268 [INFO] Created proxy listening on 127.0.0.1:58918←[0m
←[38;5;39m2023-08-31 15:31:22,269 [INFO] Using undetected_chromedriver←[0m
←[38;5;39m2023-08-31 15:31:24,073 [INFO] patching driver executable C:\Users\thesk\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe←[0m
←[38;5;39m2023-08-31 15:31:25,431 [INFO] Screen size: 1935x1030←[0m
←[38;5;39m2023-08-31 15:31:25,432 [INFO] Device size: 1880x879←[0m
←[38;5;39m2023-08-31 15:31:25,452 [INFO] [LOGIN] Logging-in...←[0m
←[38;5;39m2023-08-31 15:31:28,620 [INFO] [LOGIN] Writing email...←[0m
←[38;5;39m2023-08-31 15:31:29,780 [INFO] [LOGIN] Writing password...←[0m
←[38;5;39m2023-08-31 15:31:50,033 [INFO] [LOGIN] Logged-in !←[0m
←[38;5;39m2023-08-31 15:32:05,306 [INFO] [LOGIN] Ensuring login on Bing...←[0m
←[38;5;39m2023-08-31 15:32:11,250 [INFO] [LOGIN] Logged-in successfully !←[0m
←[38;5;39m2023-08-31 15:32:11,250 [INFO] [POINTS] You have 2,608.00 points on your account !←[0m
←[38;5;39m2023-08-31 15:32:11,251 [INFO] [SHOPPING GAME] Trying to complete the Shopping Game...←[0m
Hooked
←[38;5;39m2023-08-31 15:32:39,926 [INFO] [DAILY SET] Trying to complete the Daily Set...←[0m
←[38;5;39m2023-08-31 15:32:51,965 [INFO] [DAILY SET] Completed the Daily Set successfully !←[0m
←[38;5;39m2023-08-31 15:32:51,965 [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...←[0m
←[38;5;39m2023-08-31 15:32:59,543 [INFO] [PUNCH CARDS] Completed the Punch Cards successfully !←[0m
←[38;5;39m2023-08-31 15:33:06,459 [INFO] [MORE PROMO] Trying to complete More Promotions...←[0m
←[38;5;39m2023-08-31 15:33:06,477 [INFO] [MORE PROMO] Completed More Promotions successfully !←[0m
←[38;5;39m2023-08-31 15:33:06,495 [INFO] [POINTS] You have earned 0.00 points today !←[0m
←[38;5;39m2023-08-31 15:33:06,495 [INFO] [POINTS] You are now at 2,608.00 points !
←[0m

**Comment by theskid31** [comment]
any chance you could look into making the point counter work with this, would help to keep track 
thanks

**Comment by EastArctica** [comment]
> any chance you could look into making the point counter work with this, would help to keep track 
> 
> thanks

Yeah mean like logs like what searches have?

**Comment by theskid31** [comment]
> > any chance you could look into making the point counter work with this, would help to keep track
> > thanks
> 
> Yeah mean the logs like what the searches have?
 
Yeah please but i suppose its not registering due to it never shows completed and we get the error at
res[0] as above

**Comment by aerithanimon** [comment]
Hello, I tried the quickie script in issue 305, and the quickie script did not work.

I really do not want to use linux, just to complete the shopping game.

No one has figured out to create a brand new script, for the shopping game.

I really do not want to use the rewards farmer tool, so if EastArctica or if anyone can figure out a script for the shopping game, to be used on a windows brower, that would be appreciated.

Thanks for your time.

**Comment by theskid31** [comment]
> displaying an error like this

image

My bad, that error was supposed to be [SHOPPING GAME] Failed to select cheapest item. which happens when it fails to find the button you'd usually click to select your answer.

hi eastartica ,what is t fix for the if res[0] == 0 error
thanks

**Comment by EastArctica** [comment]
> Hello, I tried the quickie script in issue 305, and the quickie script did not work.
> 
> 
> 
> I really do not want to use linux, just to complete the shopping game.
> 
> 
> 
> No one has figured out to create a brand new script, for the shopping game.
> 
> 
> 
> I really do not want to use the rewards farmer tool, so if EastArctica or if anyone can figure out a script for the shopping game, to be used on a windows brower, that would be appreciated.
> 
> 
> 
> Thanks for your time.

Similar to what I said in the thread previously, you have 2 options. 

1. Deal with imperfect shopping game  wins.
2. Have perfect shopping games, with a custom browser extension to overwrites the js as it comes in

**Comment by Chappie18** [comment]
> > Hello, I tried the quickie script in issue 305, and the quickie script did not work.
> > I really do not want to use linux, just to complete the shopping game.
> > No one has figured out to create a brand new script, for the shopping game.
> > I really do not want to use the rewards farmer tool, so if EastArctica or if anyone can figure out a script for the shopping game, to be used on a windows brower, that would be appreciated.
> > Thanks for your time.
> 
> Similar to what I said in the thread previously, you have 2 options.
> 
> 1. Deal with imperfect shopping game  wins.
> 2. Have perfect shopping games, with a custom browser extension to overwrites the js as it comes in
> 3. Manually sent requests, people don't like this for some reason because they think they'll get banned for it. I'm like 95% sure the only way people are actually getting banned is based on _searches_ nothing else.

second option is good i guess

**Review by KrisRux — APPROVED** [review]

**Comment by EastArctica** [comment]
Anyone interested in taking this PR over be my guest, i doing have the time not interest to work on this right now.

**Pull request closed without merging**
