### PR TITLE
Add logging and use undetected-chromedriver 

### PR DESCRIPTION
**Pull request by joshuamooree**
Switch to python logging to allow terminal and log file. Also rotate log files daily.
Switch to undetected-chromedriver.  Hopefully will prevent MS detecting bot.

### CODE REVIEW

**Comment by Chappie18** [comment]
Getting this error!
image

**Comment by joshuamooree** [comment]
> I just tried using your repository, but I'm getting this problem. image

Hmm, haven't seen this error.  Looks like something is missing.  I'd try to rerun pip install -r requirements.txt and pip install selenium --upgrade .  I did both of those and I've never seen that error.  I'll see if I can reproduce this evening.

**Comment by charlesbel** [comment]
I added selenium wire and some other things to make the browser even more undetectable. Thanks for your great job !

**Comment by Loeyzen** [comment]
A bit late, but are there any legal actions that could be taken against me?

**Pull request merged**
