### PR TITLE
Fixes locale setting including UTF8

### PR DESCRIPTION
**Pull request by alceasan**
It wasn't working on linux after last update, missing parameter on setlocale()

### CODE REVIEW

**Comment by bricep** [comment]
I am getting this error around locale, maybe he is referring to this? I am on Linux as well.
image

**Comment by alceasan** [comment]
> I am getting this error around locale, maybe he is referring to this? I am on Linux as well. UPDATE: Using @alceasan 's fix, the error in the screenshot below goes away.
> 
> image

Thanks @bricep , that's the error I was having.

Aside from this problem, after the recent changes it's always forcing the locale of the country based on the IP adddress, the arguments for country and language are always overriden.

**Comment by charlesbel** [comment]
Thanks for all your messages. I see on the code that a PR changed some things so args no longer works. I'll fix that.

For locales, this PR is not the right way to fix the issue. It really depends on the computer you're using, it's not always with .utf8 (and even not on Windows). I'll fix that to work on all computers.

**Comment by charlesbel** [comment]
Fix it the right way !

**Comment by MaxDevv** [comment]
It isn't working form me

**Pull request closed without merging**
