### PR TITLE
Added Docker Support #36

### PR DESCRIPTION
**Pull request by JoshuaGarrison27**
Added Docker Support
Moved Accts into seperate file
Added Schedule feature
Updated ReadMe

I wanted this to run in Docker and now it can! I attempted to make in a useful way inside of docker without affecting anyone who wants to just run it as a script like normal. Python is not my strong language but I took a good stab at it. Let me know if there is anything else that I could have done better! Thanks

### CODE REVIEW

**Comment by JoshuaGarrison27** [comment]
After running this setup for a while, I realize that it can be kinda frustrating to have it set up this way that I have it. If the script fails for some reason then you have to wait until the next day for it to run again unless you rebuild your container with new parameters. 

So I wanted to run something past you @charlesbel and get your thoughts on it. I see that as two options:
1) Add better parameters for if running dockers so you can have more flexability to say force a run on startup of the container. This way if the script crashes unexpectedly, a simple restart of the container would help without having to worry about change up container environment variables
2) Remove the complexity of script having the schedule features and just set up the container to run once and then gracefully stop itself. Then the user can setup a CRON job to just run the container every day at a certain time. (I could write or link to some documentation for the readme)

Looking forward to getting your feedback on my thoughts. Thanks!

**Comment by JoshuaGarrison27** [comment]
- Pulled the latest files.
- Removed built in schedule feature created before this latest code
  - Makes it easier to just restart the container to run again if the script fails unexpectedly
  - Allows for the container to shut down after it completes the script (or if you want to stop it using crontab after a set amount of time)
- Added logging to a file named 'app.log'
  - This is helpful if you want to run the app on a schedule on a device such as a raspberry pi and still keep your logs. Also helps if you lose your logs from docker for some reason.

**Comment by koderian** [comment]
@charlesbel Can you merge this PR?

**Comment by charlesbel** [comment]
I'm busy but i will review it

**Pull request closed without merging**
