### PR TITLE
Add Discord Webhooks, Redeem, & Shuffle Flag

### PR DESCRIPTION
**Pull request by udu3324**
This sends a discord webhook to a channel when the bot is done with farming on an account. For #228 

Redeem flag works by first having a reward goal set for each microsoft account. (custom values on gift cards are not supported)
image

New flags: -wh -s -r
New file: discord.json (needs username and webhook url)

Thank you to #226 for providing code as reference and help.

### CODE REVIEW

**Comment by udu3324** [comment]
I haven't tested the shuffle flag yet, someone please do it

**Comment by charlesbel** [comment]
I will edit both #226 and your PR to have the same "code structure" so it will be easier to understand for future modifications

**Comment by udu3324** [comment]
im going to add -redeem flag to auto redeem things in goal

**Comment by udu3324** [comment]
The last part where you click on a button is currently not working yet. I can't figure out how to do that.
I need help
image

Note: The print() lines are temporary
I have no clue if the code works anywhere else but in the U.S, and my python knowledge is very limited.

**Comment by udu3324** [comment]
Can't test this since my account is suspended from redeeming

**Comment by udu3324** [comment]
Redeem works for me now

**Comment by charlesbel** [comment]
Removed redeem file because we need to test it, but still merging the discord option

**Pull request merged**
