### PR TITLE
Telegram Bot

### PR DESCRIPTION
**Pull request by tommaso-ascani**
I added the possibility to be up to date from a telegram bot that send messagge when start, every time it ends an account with the daily earned points and total points in the account, when the script ends with points sum of all account.

If the settings are not configured the script can run anyway, texting that the file telegram.json were create like the accounts.json file.

If you like the idea i can write the instruction in the README.md.

### CODE REVIEW

**Comment by jeffconrad18** [comment]
Hey @tommaso-ascani can you add an automatic shutdown after the Points we're earned?

**Comment by tommaso-ascani** [comment]
@jeffconrad18 shutdown of what? PC?

**Comment by jeffconrad18** [comment]
@tommaso-ascani Yes or of a RPI for example.

**Comment by tommaso-ascani** [comment]
@jeffconrad18 i'll do it when i can.
Are you using the script on RPi?

**Comment by jeffconrad18** [comment]
@tommaso-ascani yes I do.

**Comment by tommaso-ascani** [comment]
@jeffconrad18 are you using docker?

**Comment by jeffconrad18** [comment]
No, I don't.

**Pull request closed without merging**
