### PR TITLE
Mobile search fix, less CPU usage, & verbose notifs 

### PR DESCRIPTION
**Pull request by udu3324**
You can use -vn or -verbosenotifs to turn on sending all logs to which notification service you use. (discord, telegram)

Less CPU fix currently does not work

For #273, #277, and #298 

You may need to delete your sessions folder if timeout exceptions still occur

### CODE REVIEW

**Comment by Chappie18** [comment]
Thanks a lot, it performs in Telegram just as expected.
image

**Comment by MaskBoyz** [comment]
> image
> 
> Currently doesn't send any exceptions though.

Hey bro mines seems not be working if you can guide its will great

**Comment by udu3324** [comment]
> > image
> > 
> > Currently doesn't send any exceptions though.
> 
> Hey bro mines seems not be working if you can guide its will great
> 

You need to first have the  -d or -t flag, and then supply the arguments for them. Then -vn would make it verbose
So like
`python main.py -d https://discordwebhook.co -vn`

**Comment by MaskBoyz** [comment]
> > > image
> > > Currently doesn't send any exceptions though.
> > 
> > 
> > Hey bro mines seems not be working if you can guide its will great
> 
> You need to first have the -d or -t flag, and then supply the arguments for them. Then -vn would make it verbose So like `python main.py -d https://discordwebhook.co -vn`
> 
> If you have any errors screenshot them and send it here

I am not receieving any msg in my telegram or discord but everything seems to be fine

**Comment by udu3324** [comment]
> > > > image
> > > > Currently doesn't send any exceptions though.
> > > 
> > > 
> > > Hey bro mines seems not be working if you can guide its will great
> > 
> > You need to first have the -d or -t flag, and then supply the arguments for them. Then -vn would make it verbose So like `python main.py -d https://discordwebhook.co -vn`
> > 
> > If you have any errors screenshot them and send it here
> 
> I am not receieving any msg in my telegram or discord but everything seems to be fine
> 

That's strange. It should work especially discord since i test it a lot. Are you sure you setup the telegram bot correctly and have a valid chat id and key?

**Comment by MaskBoyz** [comment]
> t correctl

its not like problem with the new feature its just not working for with -t or --telegram and -d or --discord, i am just not receiving any message at all in my discord or Telegram

**Comment by MaskBoyz** [comment]
> You can use -vn or -verbosenotifs to turn on sending all logs to which notification service you use. (discord, telegram)
> 
> For #273

Working Perfectly 💜💜💜

**Comment by udu3324** [comment]
A limit of 5 has been added for Bing mobile timeouts #277 
I need testers

**Comment by theskid31** [comment]
> A limit of 5 has been added for Bing mobile timeouts, and also kind of fixed #277 I need testers

testing it from today,but only account i have has no mobile number attatched so unable to do bing mobile tests
will be running tommorow on 2 mobile accounts :smiley:

**Comment by theskid31** [comment]
> A limit of 5 has been added for Bing mobile timeouts, and also kind of fixed #277 I need testers

testing it from today,but only account i have has no mobile number attatched so unable to do bing mobile tests
will be running tommorow on 2 mobile accounts 😃

**Comment by udu3324** [comment]
> > A limit of 5 has been added for Bing mobile timeouts, and also kind of fixed #277 I need testers
> 
> Can you add any techniques to boost speed? Currently, it takes 50 minutes to finish one account.

Sure. Will do that later

**Comment by theskid31** [comment]
> 

seems to get through the mobile searches without hanging on one ,but doesnt complete them all
but i see youve updated another PR with better searches trying that tommorow

**Comment by Godielvs** [comment]
my man, this is working wonders thank you so much. before every account would stop at 5 (even on desktop), but it would only count 1-2, so i needed to open like 10-15 times to complete everything, now every account is working like clockwork

**Comment by MaskBoyz** [comment]
Its Cancelling searches when its doing Desktop Search

←[38;5;39m2023-08-22 10:47:25,879 [INFO] [MORE PROMO] Trying to complete More Promotions...←[0m
←[38;5;39m2023-08-22 10:48:55,972 [INFO] [MORE PROMO] Completed More Promotions successfully !←[0m
←[38;5;39m2023-08-22 10:48:55,982 [INFO] [BING] Starting Desktop Edge Bing searches...←[0m
←[38;5;39m2023-08-22 10:49:01,923 [INFO] [BING] 1/34←[0m
←[38;5;39m2023-08-22 10:49:22,061 [INFO] [BING] 2/34←[0m
←[38;5;196m2023-08-22 10:50:12,280 [ERROR] [BING] Timeout, retrying in 5 seconds...←[0m
←[38;5;196m2023-08-22 10:50:27,372 [ERROR] [BING] Timeout, retrying in 5 seconds...←[0m
←[38;5;196m2023-08-22 10:50:52,670 [ERROR] [BING] Timeout, retrying in 5 seconds...←[0m
←[38;5;196m2023-08-22 10:51:07,761 [ERROR] [BING] Timeout, retrying in 5 seconds...←[0m
←[38;5;196m2023-08-22 10:51:22,855 [ERROR] [BING] Timeout, retrying in 5 seconds...←[0m
←[38;5;196m2023-08-22 10:51:37,942 [ERROR] [BING] Cancelling mobile searches due to too many retries.←[0m

**Comment by theskid31** [comment]
> my man, this is working wonders thank you so much. before every account would stop at 5 (even on desktop), but it would only count 1-2, so i needed to open like 10-15 times to complete everything, now every account is working like clockwork

are you getting the quiz card and polls cards completed (i know it says success but have you checked )
as Mine doesnt seem to
but like yours its working like clockwork bar that thanks

**Comment by Godielvs** [comment]
> > my man, this is working wonders thank you so much. before every account would stop at 5 (even on desktop), but it would only count 1-2, so i needed to open like 10-15 times to complete everything, now every account is working like clockwork
> 
> are you getting the quiz card and polls cards completed (i know it says success but have you checked ) as Mine doesnt seem to but like yours its working like clockwork bar that thanks

Now that you mentioned it didn't. Also @udu3324 it seems that the browsers are not closing when finishing the script (also happening in the original code. Any idea what it could be?

**Comment by theskid31** [comment]
> > > A limit of 5 has been added for Bing mobile timeouts, and also kind of fixed #277 I need testers
> > 
> > 
> > Can you add any techniques to boost speed? Currently, it takes 50 minutes to finish one account.
> 
> Sure. Will do that later

testing your new commi of searches.py
it seems to get stuck a lot on the mobile seraches
` ←[38;5;39m2023-08-22 19:48:55,490 [INFO] Created proxy listening on 127.0.0.1:62739←[0m
←[38;5;39m2023-08-22 19:48:55,765 [INFO] Using undetected_chromedriver←[0m
←[38;5;39m2023-08-22 19:48:58,222 [INFO] patching driver executable C:\Users\thesk\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe←[0m
←[38;5;39m2023-08-22 19:48:59,795 [INFO] Screen size: 2347x1372←[0m
←[38;5;39m2023-08-22 19:49:00,220 [INFO] Device size: 2292x1221←[0m
←[38;5;39m2023-08-22 19:49:00,514 [INFO] [LOGIN] Logging-in...←[0m
←[38;5;39m2023-08-22 19:49:16,891 [INFO] [LOGIN] Logged-in !←[0m
←[38;5;39m2023-08-22 19:49:25,580 [INFO] [LOGIN] Ensuring login on Bing...←[0m
←[38;5;39m2023-08-22 19:49:31,059 [INFO] [LOGIN] Logged-in successfully !←[0m
←[38;5;39m2023-08-22 19:49:31,443 [INFO] [POINTS] You have 939.00 points on your account !←[0m
←[38;5;39m2023-08-22 19:49:31,697 [INFO] [DAILY SET] Trying to complete the Daily Set...←[0m
←[38;5;39m2023-08-22 19:49:42,254 [INFO] [DAILY SET] Completing quiz of card 2←[0m
←[38;5;39m2023-08-22 19:50:00,457 [INFO] [DAILY SET] Completing poll of card 3←[0m
←[38;5;39m2023-08-22 19:50:05,109 [INFO] [DAILY SET] Completed the Daily Set successfully !←[0m
←[38;5;39m2023-08-22 19:50:05,407 [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...←[0m
←[38;5;39m2023-08-22 19:50:10,095 [INFO] [PUNCH CARDS] Completed the Punch Cards successfully !←[0m
←[38;5;39m2023-08-22 19:50:16,893 [INFO] [MORE PROMO] Trying to complete More Promotions...←[0m
←[38;5;39m2023-08-22 19:50:53,554 [INFO] [MORE PROMO] Completed More Promotions successfully !←[0m
←[38;5;39m2023-08-22 19:50:56,444 [INFO] patching driver executable C:\Users\thesk\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe←[0m
←[38;5;39m2023-08-22 19:50:58,177 [INFO] Screen size: 405x787←[0m
←[38;5;39m2023-08-22 19:50:58,496 [INFO] Device size: 405x641←[0m
←[38;5;39m2023-08-22 19:50:58,828 [INFO] [LOGIN] Logging-in...←[0m
←[38;5;39m2023-08-22 19:51:10,798 [INFO] [LOGIN] Logged-in !←[0m
←[38;5;39m2023-08-22 19:51:22,789 [INFO] [LOGIN] Ensuring login on Bing...←[0m
←[38;5;39m2023-08-22 19:51:28,585 [INFO] [LOGIN] Logged-in successfully !←[0m
←[38;5;39m2023-08-22 19:51:28,950 [INFO] [BING] Starting Mobile Edge Bing searches...←[0m
←[38;5;39m2023-08-22 19:51:30,776 [INFO] [BING] 1/5←[0m
←[38;5;39m2023-08-22 19:51:47,152 [INFO] [BING] 2/5←[0m
←[38;5;39m2023-08-22 19:52:35,329 [INFO] [BING] 3/5←[0m
←[38;5;39m2023-08-22 19:53:21,955 [INFO] [BING] 4/5←[0m`

**Comment by udu3324** [comment]
> > > my man, this is working wonders thank you so much. before every account would stop at 5 (even on desktop), but it would only count 1-2, so i needed to open like 10-15 times to complete everything, now every account is working like clockwork
> > 
> > 
> > are you getting the quiz card and polls cards completed (i know it says success but have you checked ) as Mine doesnt seem to but like yours its working like clockwork bar that thanks
> 
> Now that you mentioned it didn't. Also @udu3324 it seems that the browsers are not closing when finishing the script (also happening in the original code. Any idea what it could be?

Not sure why.

**Comment by udu3324** [comment]
I need testers for cpu

**Comment by klept0** [comment]
telegram or discord - same name as here

**Comment by theskid31** [comment]
> I need testers for cpu

hi udu3324, I tested your cpu fix, it seemed to still leave chrome.exe instances running
I added my own chrome kill, but it will kill all instance's including if your on the browser
by using subprocess kill command in the script, simply just use edge if script is running

The mobile fixes seem never to hang now ,only issue it seems to miss the last 1 or 2 even after doing the full 20
do rerun after rerun and it does them in the script but not going through ,must be a bing issue?

**Comment by theskid31** [comment]
hi getting errors hanging always at the same place ,not each time (with multiple accounts)
found it to be verbosenotifs causing this as before i got subprocess to kill all instances of chrome.exe and undetected_chromedriver plus I got pathlib to deleted all instances of preferences file in all accounts 
they were doing there jobs but would still hang at the same place
then i tested with no arguments and would not hang
then put certain ones back on and found it to be when verbosenotifs was enabled
could you look into it thanks

error is 

> 2023-09-03 01:46:04,187 [INFO] patching driver executable C:\Users\thesk\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-09-03 01:46:05,809 [INFO] Screen size: 1152x944
2023-09-03 01:46:06,065 [INFO] Device size: 1097x793
2023-09-03 01:46:06,333 [INFO] [LOGIN] Logging-in...
2023-09-03 01:46:17,797 [INFO] [LOGIN] Logged-in !
2023-09-03 01:46:29,098 [INFO] [LOGIN] Ensuring login on Bing...
2023-09-03 01:46:35,132 [INFO] [LOGIN] Logged-in successfully !
2023-09-03 01:46:35,755 [INFO] [POINTS] You have 5,478.00 points on your account !
2023-09-03 01:46:36,033 [INFO] [DAILY SET] Trying to complete the Daily Set...
2023-09-03 01:56:40,333 [ERROR] TimeoutException: Message: timeout: Timed out receiving message from renderer: -303.661
  (Session info: chrome=116.0.5845.141)
Stacktrace:
	GetHandleVerifier [0x005C37C3+48947]
	(No symbol) [0x00558551]
	(No symbol) [0x0045C92D]
	(No symbol) [0x0044E358]
	(No symbol) [0x0044E1BA]
	(No symbol) [0x0044D09F]
	(No symbol) [0x0044D79A]
	(No symbol) [0x004579E5]
	(No symbol) [0x00463D5A]
	(No symbol) [0x00466D06]
	(No symbol) [0x0044DC5C]
	(No symbol) [0x00463C70]
	(No symbol) [0x004B76F3]
	(No symbol) [0x004A4E86]
	(No symbol) [0x004816C7]
	(No symbol) [0x0048284D]
	GetHandleVerifier [0x0080FDF9+2458985]
	GetHandleVerifier [0x0085744F+2751423]
	GetHandleVerifier [0x00851361+2726609]
	GetHandleVerifier [0x00640680+560624]
	(No symbol) [0x0056238C]
	(No symbol) [0x0055E268]
	(No symbol) [0x0055E392]
	(No symbol) [0x005510B7]
	BaseThreadInitThunk [0x76607BA9+25]
	RtlInitializeExceptionChain [0x77B4B79B+107]
	RtlClearBits [0x77B4B71F+191]
Traceback (most recent call last):
  File "F:\udu3324 Microsoft-Rewards-Farmer-master\main.py", line 25, in main
    executeBot(currentAccount, notifier, args)
  File "F:\udu3324 Microsoft-Rewards-Farmer-master\main.py", line 143, in executeBot
    DailySet(desktopBrowser).completeDailySet()
  File "F:\udu3324 Microsoft-Rewards-Farmer-master\src\dailySet.py", line 18, in completeDailySet
    self.browser.utils.goHome()
  File "F:\udu3324 Microsoft-Rewards-Farmer-master\src\utils.py", line 86, in goHome
    self.webdriver.get(BASE_URL)
  File "C:\Program Files\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 629, in get_wrapped
    return orig_get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Program Files\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -303.661
  (Session info: chrome=116.0.5845.141)
Stacktrace:
	GetHandleVerifier [0x005C37C3+48947]
	(No symbol) [0x00558551]
	(No symbol) [0x0045C92D]
	(No symbol) [0x0044E358]
	(No symbol) [0x0044E1BA]
	(No symbol) [0x0044D09F]
	(No symbol) [0x0044D79A]
	(No symbol) [0x004579E5]
	(No symbol) [0x00463D5A]
	(No symbol) [0x00466D06]
	(No symbol) [0x0044DC5C]
	(No symbol) [0x00463C70]
	(No symbol) [0x004B76F3]
	(No symbol) [0x004A4E86]
	(No symbol) [0x004816C7]
	(No symbol) [0x0048284D]
	GetHandleVerifier [0x0080FDF9+2458985]
	GetHandleVerifier [0x0085744F+2751423]
	GetHandleVerifier [0x00851361+2726609]
	GetHandleVerifier [0x00640680+560624]
	(No symbol) [0x0056238C]
	(No symbol) [0x0055E268]
	(No symbol) [0x0055E392]
	(No symbol) [0x005510B7]
	BaseThreadInitThunk [0x76607BA9+25]
	RtlInitializeExceptionChain [0x77B4B79B+107]
	RtlClearBits [0x77B4B71F+191]

**Comment by Ices-Eyes** [comment]
Hi, once implemented this fix, the mobile search works good, but the desktop one now does not arrive at the end... While previusly it was working fine the desktop, and not for the mobile :(

**Comment by udu3324** [comment]
> Hi, once implemented this fix, the mobile search works good, but the desktop one now does not arrive at the end... While previusly it was working fine the desktop, and not for the mobile :(

send a screenshot of your terminal where the bug is happening

**Comment by Ices-Eyes** [comment]
> > Hi, once implemented this fix, the mobile search works good, but the desktop one now does not arrive at the end... While previusly it was working fine the desktop, and not for the mobile :(
> 
> send a screenshot of your terminal where the bug is happening

Just then Timeout error and the ERR_HTTP2_PROTOCOL_ERROR on the borwser

image

**Comment by udu3324** [comment]
> > > Hi, once implemented this fix, the mobile search works good, but the desktop one now does not arrive at the end... While previusly it was working fine the desktop, and not for the mobile :(
> > 
> > 
> > send a screenshot of your terminal where the bug is happening
> 
> Just then Timeout error and the ERR_HTTP2_PROTOCOL_ERROR on the borwser
> 
> I guess that after a failure it would be needed to close the browser windows and start over, but I0m not sure how to implement it...
> 
> image

That isn't really a bug, it is just Microsoft rate limiting you. After 5 timeouts, it should skip the search (in 3 attempts ish)

**Comment by Ices-Eyes** [comment]
> > > > Hi, once implemented this fix, the mobile search works good, but the desktop one now does not arrive at the end... While previusly it was working fine the desktop, and not for the mobile :(
> > > 
> > > 
> > > send a screenshot of your terminal where the bug is happening
> > 
> > 
> > Just then Timeout error and the ERR_HTTP2_PROTOCOL_ERROR on the borwser
> > I guess that after a failure it would be needed to close the browser windows and start over, but I0m not sure how to implement it...
> > image
> 
> That isn't really a bug, it is just Microsoft rate limiting you. After 5 timeouts, it should skip the search (in 3 attempts ish)
> 
> Also try clearing your sessions folder

I made a try and changed the main by making it closes the browser before starting the searches (as it dows for mobile) and open a new one... That's seems to work

**Comment by TimNick151297** [comment]
Any news on the incomplete cards? Especially the quizzes are not being completed anymore for a while now. Mobile searches also seem to be incomplete (without timeout).

**Comment by GlitteringReturn** [comment]
@udu3324 why did you close this?

**Pull request closed without merging**
