### PR TITLE
Add gaming tab

### PR DESCRIPTION
**Pull request by EastArctica**
This PR adds clicking on the MSN gaming rewards card.

Currently I'm experiencing an issue where sometimes the card does not exist. I seem to get this always on other browsers like chromium however when using edge, I consistently get the card.

If anyone is available for testing please test if this finds the card for you. Also check if [this](https://www.msn.com/en-us/gaming) shows the rewards card for you.

### CODE REVIEW

**Comment by Chappie18** [comment]
I believe it appears just in the Edge browser and not in other browsers with different user agents.


image

image

**Comment by EastArctica** [comment]
> I believe it appears just in the Edge browser and not in other browsers with different user agents.
> 
> image
> 
> image

Perhaps we try setting user agent? When I tried the opposite (trying to make it *not* work on edge by changing user agent I couldn't get it to go away...)

**Comment by Chappie18** [comment]
> > I believe it appears just in the Edge browser and not in other browsers with different user agents.
> > image
> > image
> 
> Perhaps we try setting user agent? When I tried the opposite (trying to make it _not_ work on edge by changing user agent I couldn't get it to go away...)

I believe edge browser checks more than just user agents.

**Comment by theskid31** [comment]
wierd
this work via chrome

> If anyone is available for testing please test if this finds the card for you. Also check if [this](https://www.msn.com/en-us/gaming) shows the rewards card for you.

but through the bot it doesnt show i don get it?

**Review by KrisRux — APPROVED** [review]

**Comment by EastArctica** [comment]
Anyone interested in taking this PR over be my guest, i doing have the time not interest to work on this right now.

**Comment by mirra87654321** [comment]
can you accept me on discord (d0g9y) please?

**Pull request closed without merging**
